=== Rugren/archivos/LenguajeMarcas2/EjerciciosClase/24-01-31/feed.dtd
<!ELEMENT rss (channel)>
<!ATTLIST rss
    version CDATA #REQUIRED
>

<!ELEMENT channel (title, link, description, item)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT item (title, link, description, pubDate)>
<!ELEMENT pubDate (#PCDATA)>

=== Rugren/archivos/LenguajeMarcas2/EjerciciosClase/24-01-31/feed.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE rss SYSTEM "feed.dtd">

<rss version="2.0">
    <channel>
        <title>Ejemplo de Feed en RRSS</title>
        <link>http://www.ejemplo.com</link>
        <description>Este es un ejemplo de Feed en RRSS</description>
        <item>
            <title>Art√≠culo de ejemplo</title>
            <link>http://www.ejemplo.com/tarta-manzana</link>
            <description>Este es un ejemplo de Feed en RRSS</description>
            <pubDate>Mon, 06 Sep 2021 00:00:00 GMT</pubDate>
        </item>
    </channel>
</rss>
